language: csharp
mono: none
sudo: required
os: linux
dist: bionic

services:
  - docker
  
branches:
  only:
    - develop
    - master

before_script:
  - chmod -R a+x scripts
  - chmod -R a+x src

script:  
  - ./scripts/deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always    
   