######################################
#
# https://pypi.org/project/ecs-deploy/
#
# ENVIRONMENT VARIABLES
#   -  SERVICE_NAME = container name in ECS Task e.g. churchmanager-api
#   -  ECR_REPOSITORY_URI = the container registry for this
#   -  ENVIRONMENT = passed in based on the branch built e.g. develop=Test, master=Production
#
#####################################

sudo: required
dist: xenial
language: python
mono: none
python: 3.9
services:
    - docker

branches:
    only:
        - develop
        - master
env:
    - TIMESTAMP=$(date '+%Y%m%d') IMAGE_TAG="${TIMESTAMP}-${TRAVIS_BUILD_NUMBER:=latest}" IMAGE_URI="$ECR_REPOSITORY_URI:$IMAGE_TAG"

before_install:
    - pip install --upgrade awscli
    - pip install --upgrade ecs-deploy
    - export PATH=$PATH:$HOME/.local/bin

script:
    - $(aws ecr get-login --no-include-email)
    - docker build -t $ECR_REPOSITORY_URI:latest .
    - docker tag $ECR_REPOSITORY_URI:latest $ECR_REPOSITORY_URI:$IMAGE_TAG
    - docker push $ECR_REPOSITORY_URI:latest
    - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
    
# Just some logging    
before_deploy:
    - echo $IMAGE_TAG

deploy:
    # deploy master to production
    - provider: script
      script: ecs deploy $CLUSTER_NAME prod-$SERVICE_NAME-service --tag $IMAGE_TAG -e $SERVICE_NAME ASPNETCORE_ENVIRONMENT $ENVIRONMENT
      on:
        branch: master
    # deploy develop to the test environment
    - provider: script
      script: ecs deploy $CLUSTER_NAME test-$SERVICE_NAME-service --tag $IMAGE_TAG -e $SERVICE_NAME ASPNETCORE_ENVIRONMENT $ENVIRONMENT
      on:
        branch: develop

notifications:
    email:
        on_success: never
        on_failure: always