using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChurchManager.Application.Features.Groups.Services;
using ChurchManager.Domain.Features.Groups;
using ChurchManager.Infrastructure.Persistence.Contexts;
using ChurchManager.Infrastructure.Persistence.Repositories;
using Microsoft.EntityFrameworkCore;
using Xunit;
using Xunit.Abstractions;

namespace ChurchManager.Infrastructure.Persistence.Tests
{
    public class GroupDbRepository_Tests
    {
        private readonly ITestOutputHelper _output;

        private readonly DbContextOptions<ChurchManagerDbContext> _options = new DbContextOptionsBuilder<ChurchManagerDbContext>()
            .UseNpgsql("Server=localhost;Port=5432;Database=churchmanager_db;User Id=admin;password=P455word1;")
            //.UseLoggerFactory(_loggerFactory) //Optional, this logs SQL generated by EF Core to the Console
            .Options;

        public GroupDbRepository_Tests(ITestOutputHelper output)
        {
            _output = output;
        }

        [Fact]
        public async Task Should_construct_group_tree()
        {
            using (var dbContext = new ChurchManagerDbContext(_options))
            {
                var dbRepository = new GroupDbRepository(dbContext);

                // This is bad
                var groups = await dbRepository.Queryable()
                    .AsNoTracking()
                    .Include(x => x.Groups)
                    .ToListAsync();

                BuildMenu(groups);

                // This is better
                var better = await dbRepository.GroupsWithChildrenAsync(10);
            }
        }

        [Fact]
        public async Task Should_return_group_roles_for_group_GroupService()
        {
            using(var dbContext = new ChurchManagerDbContext(_options))
            {
                var dbRepository = new GroupDbRepository(dbContext);
                var service = new GroupsService(dbRepository);

                // This is bad
                var roles = await service.GroupRolesForGroupAsync(1);

                Assert.NotEmpty(roles);
            }
        }


        void BuildMenu(IEnumerable<Group> data, int? parentId = null)
        {
            var items = data.Where(d => d.ParentGroupId == parentId).OrderBy(i => i.Id).ToList();
            if(items.Any())
            {
                foreach (var item in items)
                {
                    _output.WriteLine("\t" + item.Name);
                    BuildMenu(data, item.Id);
                }
            }
        }
    }
}
